### ISSUE TITLE
Typo in question

### ISSUE THREAD

**Issue by ahmedovv123** [x676f64/secureum-mind_map#20]
[quizzes](https://github.com/x676f64/secureum-mind_map/tree/master/quizzes)/2. Solidity 101/[Q7](https://github.com/x676f64/secureum-mind_map/blob/master/quizzes/2.%20Solidity%20101.md#q7-which-of-the-following-isare-true-above-events)

perhaps "about" was meant instead of "above"?

**Comment by x676f64** [comment]
Addressed here https://github.com/x676f64/secureum-mind_map/pull/21

**Comment by x676f64** [comment]
Should be good. https://github.com/x676f64/secureum-mind_map/pull/21
